### ISSUE TITLE
Mitigating redirection

### ISSUE THREAD

**Issue by mozfreddyb** [mikewest/injection-mitigated#1]
I think this is just a nit pick, but...
The "Does a policy sufficiently mitigate redirection?" algorithm seems to only look at the `base-uri` CSP directive.
With that, it prevents redirecting relative URLs to other origins/pages.

From the namre of the check, it did seem odd that this isn't considering redirects of _the current document_ to a different spoofy page (e.g., injecting `<meta redirect>` or `<iframe>` where embedded document can navigate `top` etc.).

Is that something worth considering? If not, why?

<footer>Writing all of this down right now, I think I know the answer. But I'm still going to post for the sake of having a discussion :)

<details><summary>Spoiler</summary>It's likely because the redirected spoof page would just be a different page that does not get access to the origin under attack. Though the target page might qualify to gain access to APIs that are guarded behind the new `[InjectionMitigated]` anyway.

**Comment by mikewest** [comment]
1. "Redirection" is just a bad name for the check. When I wrote it, I was thinking of `<base href="https://evil.com/">` "redirecting" `<script src="/whatever.js">` to `https://evil.com/whatever.js`, but you're right to point it out as confusing. Perhaps "relative URL manipulation" would be more accurate?

1.  `<meta>` refresh and `<iframe>` to unexpected locations are, as you spoiled for yourself, contexts that have to qualify for capabilities on their own. They can't launder their desires through a better-behaved site's qualification.

_Tangentially, I would be happier if we could consider `<meta>`'s navigations as inline script. https://chromestatus.com/metrics/feature/timeline/popularity/1550 suggests than ~0.11% of pages  would be affected in Chrome, which has been too high for me to go poking at._

**Comment by mozfreddyb** [comment]
1) "relative URL manipulation" would be more expressive for sure. 
2) Yup
3) Tangentially, that would be really nice. But I agree that 0.11% might be too high.

**Comment by mikewest** [comment]
1. Changed the name, thanks!
2. Yup.
3. Yup. :)
